/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sim.tricycle.ihm;

import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.BoxLayout;
import javax.swing.JComboBox;
import javax.swing.PopupFactory;

/**
 *
 * @author morgan
 */
public final class FrameTeamMaker extends javax.swing.JFrame {

    /**
     * Creates new form FrameTeamMaker
     */
    private int teamNumber = 1;
    private int maxAutoByTeam = 3;
    private int defaultHeight;
    private PopupFactory ppFtry = new PopupFactory();

    public FrameTeamMaker() {
        initComponents();

        this.setLayout(new BorderLayout());
        this.add(panTitile, BorderLayout.PAGE_START);
        this.add(panFooter, BorderLayout.PAGE_END);
        this.add(tabPanTeams, BorderLayout.CENTER);

        this.defaultHeight = this.getSize().height;
//        javax.swing.JPanel panTeam = new javax.swing.JPanel();
//        tabPanTeams.addTab("team", panTeam);
//
//        panTeam.setLayout(new BoxLayout(panTeam, BoxLayout.Y_AXIS));
//
//        PanSelectAutomate panSelect = new PanSelectAutomate();
//        panTeam.add(panSelect);
//
//        System.out.println("hauteur frame : " + this.getHeight() + " taille pan :" + panSelect.getPreferredSize().height);
//         this.setSize(this.getWidth(), this.getHeight() + panSelect.getPreferredSize().height);
//
//        PanSelectAutomate panSelect1 = new PanSelectAutomate();
//        panTeam.add(panSelect1);
//
//        this.setSize(this.getWidth(), this.getHeight() + panSelect1.getPreferredSize().height);
//
//        PanSelectAutomate panSelect2 = new PanSelectAutomate();
//        panTeam.add(panSelect2);
//
//        this.setSize(this.getWidth(), this.getHeight() + panSelect2.getPreferredSize().height);
//        
//        javax.swing.JPanel panTeam2 = new javax.swing.JPanel();
//        tabPanTeams.addTab("team2", panTeam2);

        System.out.println("hauteur frame : " + this.getHeight() + " taille pan :" + tabPanTeams.getPreferredSize().height);

        while (teamNumber <= 3) {
            javax.swing.JPanel newPanTeam = createPanTeam();
            addTabTeam(tabPanTeams, newPanTeam);
            //addPanAutomate(newPanTeam);
            // updateHeight(newPanTeam);
        }

    }

    public void addTabTeam(javax.swing.JTabbedPane tabpan, javax.swing.JPanel panteam) {
        String titleTab = "Team " + teamNumber;
        tabpan.addTab(titleTab, panteam);
        teamNumber++;
    }

    public void addPanAutomate(javax.swing.JPanel pan) {
        if (pan.getComponents().length <= maxAutoByTeam) {
            PanSelectAutomate panSelect = new PanSelectAutomate();
            pan.add(panSelect);
            updateHeight(pan);
        } else {
            //TODO si temps ... pop up pour dire qu'on en fait pas plus
            //ppFtry.getPopup(this, "Coucou", 100, 100).show());      
        }
        //this.setSize(this.getWidth(), this.getHeight() + panSelect.getPreferredSize().height);
    }

    public void removePanAutomate(javax.swing.JPanel pan) {
        if (pan.getComponents().length >= 2) {
            pan.remove(pan.getComponent(pan.getComponents().length - 1));
            updateHeight(pan);
        }
    }

    public javax.swing.JPanel createPanTeam() {
        javax.swing.JPanel panteam = new javax.swing.JPanel();
        panteam.setLayout(new BoxLayout(panteam, BoxLayout.Y_AXIS));
        addPanAutomate(panteam);
        return panteam;
    }

    public void updateHeight(javax.swing.JPanel pan) {
        int numberComponent = pan.getComponents().length;
        this.setSize(this.getWidth(), defaultHeight + numberComponent * new PanSelectAutomate().getPreferredSize().height);
    }

    public boolean isValidPan(javax.swing.JPanel pan) {
        Component[] tabComp = pan.getComponents();
        for (Component c : tabComp) {
            if (c instanceof PanSelectAutomate) {
                if (!(((PanSelectAutomate) c).isValidPanAuto())) {
                    return false;
                }
            }
        }
        return true;
    }

    public boolean isValidFrame() {
        for (int i = 0; i < tabPanTeams.getTabCount(); i++) {
            Component c = tabPanTeams.getTabComponentAt(i);
            if (c instanceof javax.swing.JPanel) {
                if (!isValidPan((javax.swing.JPanel)c))
                    return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddMod1 = new javax.swing.JButton();
        panTitile = new javax.swing.JPanel();
        lblSentence = new javax.swing.JLabel();
        panHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panFooter = new javax.swing.JPanel();
        btnAddMod = new javax.swing.JButton();
        btnValid = new javax.swing.JButton();
        btnRemoveMod = new javax.swing.JButton();
        tabPanTeams = new javax.swing.JTabbedPane();

        btnAddMod1.setText("Add Model");
        btnAddMod1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMod1MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panTitile.setBorder(null);

        lblSentence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSentence.setText("Choose your automates and associate an image for each one of them. Max 3 differents automates");

        panHeader.setBackground(new java.awt.Color(85, 81, 78));
        panHeader.setBorder(null);
        panHeader.setForeground(new java.awt.Color(253, 251, 251));

        lblTitle.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(254, 254, 254));
        lblTitle.setText("Make the teams");

        javax.swing.GroupLayout panHeaderLayout = new javax.swing.GroupLayout(panHeader);
        panHeader.setLayout(panHeaderLayout);
        panHeaderLayout.setHorizontalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panHeaderLayout.setVerticalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHeaderLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap())
        );

        javax.swing.GroupLayout panTitileLayout = new javax.swing.GroupLayout(panTitile);
        panTitile.setLayout(panTitileLayout);
        panTitileLayout.setHorizontalGroup(
            panTitileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panTitileLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblSentence)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        panTitileLayout.setVerticalGroup(
            panTitileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTitileLayout.createSequentialGroup()
                .addComponent(panHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSentence)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panFooter.setBorder(null);

        btnAddMod.setText("Add Model");
        btnAddMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddModMouseClicked(evt);
            }
        });

        btnValid.setText("Validate");
        btnValid.setEnabled(false);

        btnRemoveMod.setText("Remove Model");
        btnRemoveMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveModMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panFooterLayout = new javax.swing.GroupLayout(panFooter);
        panFooter.setLayout(panFooterLayout);
        panFooterLayout.setHorizontalGroup(
            panFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFooterLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(btnAddMod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoveMod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnValid, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panFooterLayout.setVerticalGroup(
            panFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValid)
                    .addComponent(btnAddMod)
                    .addComponent(btnRemoveMod))
                .addContainerGap())
        );

        tabPanTeams.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPanTeamsStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panTitile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabPanTeams))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panTitile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabPanTeams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddModMouseClicked
        // TODO add your handling code here:
        //addPanAutomate((javax.swing.JPanel)tabPanTeams.getTabComponentAt(tabPanTeams.getSelectedIndex()));
        addPanAutomate((javax.swing.JPanel) tabPanTeams.getSelectedComponent());
    }//GEN-LAST:event_btnAddModMouseClicked

    private void tabPanTeamsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPanTeamsStateChanged
        // TODO add your handling code here:
        updateHeight((javax.swing.JPanel) tabPanTeams.getSelectedComponent());
    }//GEN-LAST:event_tabPanTeamsStateChanged

    private void btnAddMod1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMod1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMod1MouseClicked

    private void btnRemoveModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveModMouseClicked
        // TODO add your handling code here:
        removePanAutomate((javax.swing.JPanel) tabPanTeams.getSelectedComponent());
    }//GEN-LAST:event_btnRemoveModMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTeamMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTeamMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTeamMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTeamMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrameTeamMaker().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMod;
    private javax.swing.JButton btnAddMod1;
    private javax.swing.JButton btnRemoveMod;
    private javax.swing.JButton btnValid;
    private javax.swing.JLabel lblSentence;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panFooter;
    private javax.swing.JPanel panHeader;
    private javax.swing.JPanel panTitile;
    private javax.swing.JTabbedPane tabPanTeams;
    // End of variables declaration//GEN-END:variables
}
