/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sim.tricycle.ihm;

/**
 *
 * @author morgan
 */
public class PanelSelectAutomate extends javax.swing.JFrame {

    /**
     * Creates new form PanelSelectAutomate
     */
    public PanelSelectAutomate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panSelectModel = new javax.swing.JPanel();
        panImageAuto = new javax.swing.JPanel();
        cbxAutoImage = new javax.swing.JComboBox();
        cbxAutomate = new javax.swing.JComboBox();
        lblAutomate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panSelectModel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First Model", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        panImageAuto.setBackground(new java.awt.Color(1, 1, 1));

        javax.swing.GroupLayout panImageAutoLayout = new javax.swing.GroupLayout(panImageAuto);
        panImageAuto.setLayout(panImageAutoLayout);
        panImageAutoLayout.setHorizontalGroup(
            panImageAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );
        panImageAutoLayout.setVerticalGroup(
            panImageAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        cbxAutoImage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxAutomate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblAutomate.setText("Automate :");

        javax.swing.GroupLayout panSelectModelLayout = new javax.swing.GroupLayout(panSelectModel);
        panSelectModel.setLayout(panSelectModelLayout);
        panSelectModelLayout.setHorizontalGroup(
            panSelectModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSelectModelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panImageAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cbxAutoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(lblAutomate)
                .addGap(34, 34, 34)
                .addComponent(cbxAutomate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panSelectModelLayout.setVerticalGroup(
            panSelectModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSelectModelLayout.createSequentialGroup()
                .addComponent(panImageAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(panSelectModelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panSelectModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAutoImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAutomate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAutomate))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panSelectModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panSelectModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelSelectAutomate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelSelectAutomate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelSelectAutomate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelSelectAutomate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PanelSelectAutomate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxAutoImage;
    private javax.swing.JComboBox cbxAutomate;
    private javax.swing.JLabel lblAutomate;
    private javax.swing.JPanel panAutoImage;
    private javax.swing.JPanel panAutoImage1;
    private javax.swing.JPanel panAutoImage2;
    private javax.swing.JPanel panAutoImage3;
    private javax.swing.JPanel panAutoImage4;
    private javax.swing.JPanel panAutoImage5;
    private javax.swing.JPanel panImageAuto;
    private javax.swing.JPanel panSelectAutomate;
    private javax.swing.JPanel panSelectAutomate1;
    private javax.swing.JPanel panSelectAutomate2;
    private javax.swing.JPanel panSelectAutomate3;
    private javax.swing.JPanel panSelectAutomate4;
    private javax.swing.JPanel panSelectAutomate5;
    private javax.swing.JPanel panSelectModel;
    // End of variables declaration//GEN-END:variables
}
