/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sim.tricycle.ihm;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import sim.tricycle.robot.Model;

/**
 *
 * @author morgan
 */
public class PanSelectModel extends javax.swing.JPanel {

    private Model model;
    
    /**
     * Creates new form PanSelectModel
     */
    public PanSelectModel(Model mod) {
        initComponents();
        this.model = mod;
        lblNameauto.setText(model.getImg());
//        lblGoldValue.setText(model.getRob().getPrix());
    }

    @Override
    public void paint(Graphics graphic) {
        super.paint(graphic);
        Graphics2D g = (Graphics2D) graphic;

        Image imgBot = null;
        try {//TODO ne pas faire IO mais chercher dans les images enregistré dans la frame
            imgBot = ImageIO.read(new File("./src/sim/tricycle/ihm/images/robots/" + model.getImg()));
        } catch (IOException ex) {
            Logger.getLogger(PanSelectAutomate.class.getName()).log(Level.SEVERE, null, ex);
        }

        g.drawImage(imgBot, 20, 20, 60, 60, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNameauto = new javax.swing.JLabel();
        lblGold = new javax.swing.JLabel();
        lblGoldValue = new javax.swing.JLabel();
        btnCreateBot = new javax.swing.JButton();

        setBackground(java.awt.Color.lightGray);
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(262, 113));

        lblNameauto.setText("jLabel1");

        lblGold.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblGold.setText("Gold :");

        lblGoldValue.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblGoldValue.setText("jLabel3");

        btnCreateBot.setText("Create");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNameauto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGold)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGoldValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCreateBot, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGold)
                    .addComponent(lblGoldValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateBot)
                    .addComponent(lblNameauto))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateBot;
    private javax.swing.JLabel lblGold;
    private javax.swing.JLabel lblGoldValue;
    private javax.swing.JLabel lblNameauto;
    // End of variables declaration//GEN-END:variables
}
