/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sim.tricycle.ihm;

/**
 *
 * @author morgan
 */
public class PanSelectAutomate extends javax.swing.JPanel {

    /**
     * Creates new form PanSelectAutomate
     */
    public PanSelectAutomate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panSelectModel = new javax.swing.JPanel();
        panImageAuto = new javax.swing.JPanel();
        cbxAutoImage = new javax.swing.JComboBox();
        cbxAutomate = new javax.swing.JComboBox();
        lblAutomate = new javax.swing.JLabel();

        panSelectModel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        panImageAuto.setBackground(new java.awt.Color(1, 1, 1));

        javax.swing.GroupLayout panImageAutoLayout = new javax.swing.GroupLayout(panImageAuto);
        panImageAuto.setLayout(panImageAutoLayout);
        panImageAutoLayout.setHorizontalGroup(
            panImageAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );
        panImageAutoLayout.setVerticalGroup(
            panImageAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        cbxAutoImage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxAutomate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblAutomate.setText("Automate :");

        javax.swing.GroupLayout panSelectModelLayout = new javax.swing.GroupLayout(panSelectModel);
        panSelectModel.setLayout(panSelectModelLayout);
        panSelectModelLayout.setHorizontalGroup(
            panSelectModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSelectModelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(panImageAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cbxAutoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(lblAutomate)
                .addGap(34, 34, 34)
                .addComponent(cbxAutomate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panSelectModelLayout.setVerticalGroup(
            panSelectModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSelectModelLayout.createSequentialGroup()
                .addComponent(panImageAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(panSelectModelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panSelectModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAutoImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAutomate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAutomate))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panSelectModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panSelectModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxAutoImage;
    private javax.swing.JComboBox cbxAutomate;
    private javax.swing.JLabel lblAutomate;
    private javax.swing.JPanel panImageAuto;
    private javax.swing.JPanel panSelectModel;
    // End of variables declaration//GEN-END:variables
}
