/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sim.tricycle.ihm;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.geom.Rectangle2D;
import javax.swing.border.LineBorder;
import sim.tricycle.mapping.Case;
import sim.tricycle.mapping.CarteInterface;

/**
 *
 * @author nell
 */
public class ViewCarte extends javax.swing.JPanel {

    private CarteInterface carte;

    /**
     * Creates new form ViewCarte
     */
    public ViewCarte(CarteInterface carte) {
        initComponents();
        this.setBorder(new LineBorder(Color.BLACK));
        this.carte = carte;
    }

    @Override
    public void paint(Graphics graphic) {
        super.paint(graphic);
        Graphics2D g = (Graphics2D) graphic;        
        
        int maxWidth = this.getWidth() / carte.getLargeur();
        int maxHeight = this.getHeight() / carte.getHauteur();
        int maxSize = Math.min(maxHeight, maxWidth);
        
        for (int i = 0; i < carte.getHauteur(); i++) {
            for (int j = 0; j < carte.getLargeur(); j++) {
                paintCase(g, carte.getCase(i, j), maxSize);
            }
        }
    }

    private void paintCase(Graphics2D g, Case c, int width) {
        System.out.println("Paint case " +width + "/" + c.getX() + " " + c.getY());
        int x = c.getX() * width;
        int y = c.getY() * width;
        g.drawRect(x, y, width, width);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
